/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountType = IDL.Variant({
  'liabilities' : IDL.Null,
  'revenue' : IDL.Null,
  'expenses' : IDL.Null,
  'assets' : IDL.Null,
  'equity' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'repair' : IDL.Null,
  'cleaning' : IDL.Null,
  'other' : IDL.Text,
  'consulting' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const Time = IDL.Int;
export const UserRegistration = IDL.Record({
  'status' : ApprovalStatus,
  'paypalTransactionId' : IDL.Text,
  'principal' : IDL.Principal,
  'subscriptionTier' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'serviceType' : ServiceType,
  'dateRequested' : Time,
  'customer' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
});
export const Shipment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
  }),
  'destination' : IDL.Text,
  'contents' : IDL.Text,
  'createdBy' : IDL.Principal,
  'origin' : IDL.Text,
  'shippingMethod' : IDL.Text,
  'deliveryDate' : Time,
  'shippingDate' : Time,
  'price' : IDL.Float64,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'journal' : IDL.Text,
  'description' : IDL.Text,
  'account' : IDL.Text,
  'amount' : IDL.Float64,
  'transactionId' : IDL.Nat,
});
export const AccountingTransaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : AccountType,
  'journalEntries' : IDL.Vec(JournalEntry),
  'date' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'balanceShipping' : IDL.Float64,
  'businessName' : IDL.Text,
  'shippingPackages' : IDL.Vec(IDL.Text),
  'warehouseLocation' : IDL.Text,
  'businessSector' : IDL.Text,
  'turnoverRegion' : IDL.Nat,
  'activeInvoices' : IDL.Vec(IDL.Text),
  'balanceGeneralGoods' : IDL.Float64,
});
export const ApprovalStatus__1 = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus__1,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addInventory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addPaymentAccount' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'addSupplier' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateBalance' : IDL.Func([AccountType], [IDL.Float64], ['query']),
  'createServiceRequest' : IDL.Func(
      [ServiceType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createShipment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
  'deleteShipment' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getActiveEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllCustomers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllInventory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllPaymentAccounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(UserRegistration)], ['query']),
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getAllSuppliers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllTransactions' : IDL.Func(
      [],
      [IDL.Vec(AccountingTransaction)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerRegistrationStatus' : IDL.Func(
      [],
      [IDL.Opt(ApprovalStatus)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
  'getEmployeesByRole' : IDL.Func([IDL.Text], [IDL.Vec(Employee)], ['query']),
  'getInventory' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getPaymentAccount' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Float64)], ['query']),
  'getServiceRequestsByStatus' : IDL.Func(
      [
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getShipment' : IDL.Func([IDL.Nat], [IDL.Opt(Shipment)], ['query']),
  'getShipmentsByCaller' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getShipmentsByStatus' : IDL.Func(
      [
        IDL.Variant({
          'pending' : IDL.Null,
          'inTransit' : IDL.Null,
          'delivered' : IDL.Null,
        }),
      ],
      [IDL.Vec(Shipment)],
      ['query'],
    ),
  'getSupplier' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getTransaction' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AccountingTransaction)],
      ['query'],
    ),
  'getTransactionsByType' : IDL.Func(
      [AccountType],
      [IDL.Vec(AccountingTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'recordTransaction' : IDL.Func(
      [IDL.Int, IDL.Float64, IDL.Text, AccountType, IDL.Vec(JournalEntry)],
      [IDL.Nat],
      [],
    ),
  'removeInventory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus__1], [], []),
  'submitRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'transferPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'updateEmployee' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updatePaymentAccount' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateRegistrationStatus' : IDL.Func(
      [IDL.Principal, ApprovalStatus],
      [],
      [],
    ),
  'updateServiceRequestStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateShipmentStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'inTransit' : IDL.Null,
          'delivered' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountType = IDL.Variant({
    'liabilities' : IDL.Null,
    'revenue' : IDL.Null,
    'expenses' : IDL.Null,
    'assets' : IDL.Null,
    'equity' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'repair' : IDL.Null,
    'cleaning' : IDL.Null,
    'other' : IDL.Text,
    'consulting' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserRegistration = IDL.Record({
    'status' : ApprovalStatus,
    'paypalTransactionId' : IDL.Text,
    'principal' : IDL.Principal,
    'subscriptionTier' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'serviceType' : ServiceType,
    'dateRequested' : Time,
    'customer' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
  });
  const Shipment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'inTransit' : IDL.Null,
      'delivered' : IDL.Null,
    }),
    'destination' : IDL.Text,
    'contents' : IDL.Text,
    'createdBy' : IDL.Principal,
    'origin' : IDL.Text,
    'shippingMethod' : IDL.Text,
    'deliveryDate' : Time,
    'shippingDate' : Time,
    'price' : IDL.Float64,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'journal' : IDL.Text,
    'description' : IDL.Text,
    'account' : IDL.Text,
    'amount' : IDL.Float64,
    'transactionId' : IDL.Nat,
  });
  const AccountingTransaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : AccountType,
    'journalEntries' : IDL.Vec(JournalEntry),
    'date' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'balanceShipping' : IDL.Float64,
    'businessName' : IDL.Text,
    'shippingPackages' : IDL.Vec(IDL.Text),
    'warehouseLocation' : IDL.Text,
    'businessSector' : IDL.Text,
    'turnoverRegion' : IDL.Nat,
    'activeInvoices' : IDL.Vec(IDL.Text),
    'balanceGeneralGoods' : IDL.Float64,
  });
  const ApprovalStatus__1 = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus__1,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addInventory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addPaymentAccount' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'addSupplier' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateBalance' : IDL.Func([AccountType], [IDL.Float64], ['query']),
    'createServiceRequest' : IDL.Func(
        [ServiceType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createShipment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
    'deleteShipment' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getActiveEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllCustomers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllInventory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllPaymentAccounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getAllRegistrations' : IDL.Func(
        [],
        [IDL.Vec(UserRegistration)],
        ['query'],
      ),
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getAllSuppliers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func(
        [],
        [IDL.Vec(AccountingTransaction)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerRegistrationStatus' : IDL.Func(
        [],
        [IDL.Opt(ApprovalStatus)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
    'getEmployeesByRole' : IDL.Func([IDL.Text], [IDL.Vec(Employee)], ['query']),
    'getInventory' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getPaymentAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getServiceRequestsByStatus' : IDL.Func(
        [
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getShipment' : IDL.Func([IDL.Nat], [IDL.Opt(Shipment)], ['query']),
    'getShipmentsByCaller' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getShipmentsByStatus' : IDL.Func(
        [
          IDL.Variant({
            'pending' : IDL.Null,
            'inTransit' : IDL.Null,
            'delivered' : IDL.Null,
          }),
        ],
        [IDL.Vec(Shipment)],
        ['query'],
      ),
    'getSupplier' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getTransaction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AccountingTransaction)],
        ['query'],
      ),
    'getTransactionsByType' : IDL.Func(
        [AccountType],
        [IDL.Vec(AccountingTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'recordTransaction' : IDL.Func(
        [IDL.Int, IDL.Float64, IDL.Text, AccountType, IDL.Vec(JournalEntry)],
        [IDL.Nat],
        [],
      ),
    'removeInventory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus__1], [], []),
    'submitRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transferPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'updateEmployee' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updatePaymentAccount' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateRegistrationStatus' : IDL.Func(
        [IDL.Principal, ApprovalStatus],
        [],
        [],
      ),
    'updateServiceRequestStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateShipmentStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'inTransit' : IDL.Null,
            'delivered' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };