/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'liabilities' : null } |
  { 'revenue' : null } |
  { 'expenses' : null } |
  { 'assets' : null } |
  { 'equity' : null };
export interface AccountingTransaction {
  'id' : bigint,
  'transactionType' : AccountType,
  'journalEntries' : Array<JournalEntry>,
  'date' : bigint,
  'description' : string,
  'amount' : number,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export type ApprovalStatus__1 = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Employee {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'isActive' : boolean,
  'email' : string,
}
export interface JournalEntry {
  'id' : bigint,
  'date' : bigint,
  'journal' : string,
  'description' : string,
  'account' : string,
  'amount' : number,
  'transactionId' : bigint,
}
export interface ServiceRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'inProgress' : null },
  'serviceType' : ServiceType,
  'dateRequested' : Time,
  'customer' : string,
  'createdBy' : Principal,
  'description' : string,
}
export type ServiceType = { 'repair' : null } |
  { 'cleaning' : null } |
  { 'other' : string } |
  { 'consulting' : null } |
  { 'maintenance' : null };
export interface Shipment {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'inTransit' : null } |
    { 'delivered' : null },
  'destination' : string,
  'contents' : string,
  'createdBy' : Principal,
  'origin' : string,
  'shippingMethod' : string,
  'deliveryDate' : Time,
  'shippingDate' : Time,
  'price' : number,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus__1,
  'principal' : Principal,
}
export interface UserProfile {
  'id' : bigint,
  'contactInfo' : string,
  'balanceShipping' : number,
  'businessName' : string,
  'shippingPackages' : Array<string>,
  'warehouseLocation' : string,
  'businessSector' : string,
  'turnoverRegion' : bigint,
  'activeInvoices' : Array<string>,
  'balanceGeneralGoods' : number,
}
export interface UserRegistration {
  'status' : ApprovalStatus,
  'paypalTransactionId' : string,
  'principal' : Principal,
  'subscriptionTier' : string,
  'fullName' : string,
  'email' : string,
  'timestamp' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[string, string], undefined>,
  'addEmployee' : ActorMethod<[string, string, string, boolean], bigint>,
  'addInventory' : ActorMethod<[string, bigint], undefined>,
  'addPaymentAccount' : ActorMethod<[string, number], undefined>,
  'addSupplier' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateBalance' : ActorMethod<[AccountType], number>,
  'createServiceRequest' : ActorMethod<[ServiceType, string, string], bigint>,
  'createShipment' : ActorMethod<
    [string, string, string, string, number],
    bigint
  >,
  'deleteEmployee' : ActorMethod<[bigint], undefined>,
  'deleteShipment' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getActiveEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllCustomers' : ActorMethod<[], Array<[string, string]>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllInventory' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllPaymentAccounts' : ActorMethod<[], Array<[string, number]>>,
  'getAllRegistrations' : ActorMethod<[], Array<UserRegistration>>,
  'getAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getAllShipments' : ActorMethod<[], Array<Shipment>>,
  'getAllSuppliers' : ActorMethod<[], Array<[string, string]>>,
  'getAllTransactions' : ActorMethod<[], Array<AccountingTransaction>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerRegistrationStatus' : ActorMethod<[], [] | [ApprovalStatus]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], [] | [string]>,
  'getEmployee' : ActorMethod<[bigint], [] | [Employee]>,
  'getEmployeesByRole' : ActorMethod<[string], Array<Employee>>,
  'getInventory' : ActorMethod<[string], [] | [bigint]>,
  'getPaymentAccount' : ActorMethod<[string], [] | [number]>,
  'getServiceRequestsByStatus' : ActorMethod<
    [{ 'pending' : null } | { 'completed' : null } | { 'inProgress' : null }],
    Array<ServiceRequest>
  >,
  'getShipment' : ActorMethod<[bigint], [] | [Shipment]>,
  'getShipmentsByCaller' : ActorMethod<[], Array<Shipment>>,
  'getShipmentsByStatus' : ActorMethod<
    [{ 'pending' : null } | { 'inTransit' : null } | { 'delivered' : null }],
    Array<Shipment>
  >,
  'getSupplier' : ActorMethod<[string], [] | [string]>,
  'getTransaction' : ActorMethod<[bigint], [] | [AccountingTransaction]>,
  'getTransactionsByType' : ActorMethod<
    [AccountType],
    Array<AccountingTransaction>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'recordTransaction' : ActorMethod<
    [bigint, number, string, AccountType, Array<JournalEntry>],
    bigint
  >,
  'removeInventory' : ActorMethod<[string, bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus__1], undefined>,
  'submitRegistration' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'transferPayment' : ActorMethod<[string, string, number], undefined>,
  'updateEmployee' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
  'updatePaymentAccount' : ActorMethod<[string, number], undefined>,
  'updateRegistrationStatus' : ActorMethod<
    [Principal, ApprovalStatus],
    undefined
  >,
  'updateServiceRequestStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'completed' : null } |
        { 'inProgress' : null },
    ],
    undefined
  >,
  'updateShipmentStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'inTransit' : null } |
        { 'delivered' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];